version: "3.9"

services:
  rc_rds:
    image: redis/redis-stack-server:7.2.0-v4
    container_name: rc_rds
    ports:
      - 0.0.0.0:6379:6379
    volumes:
      - ./data/redis:/data/
      - ./config/redis/redis.conf:/etc/redis/redis.conf
      - ./config/redis/users.acl:/etc/redis/users.acl
    command: redis-server /etc/redis/redis.conf

  rc_rds_adm:
    image: redislabs/redisinsight:latest
    container_name: rc_rds_adm
    ports:
      - 127.0.0.1:8001:8001